# docker-compose file is managed by puppet
version: '3.5'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    volumes:
      - /net/systems/radarr:/config
      - /net/media/movies:/movies
      - /net/systems/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
    environment:
      - TZ=America/Montreal
      - PGID=1011
      - PUID=1011
    network_mode: host
    volumes:
      - /net/systems/transmission/config:/config
      - /net/systems/downloads:/downloads
      - /net/systems/downloads/watch:/watch
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    network_mode: host
    volumes:
      - /net/systems/sonarr:/config
      - /net/media/series:/series
      - /net/systems/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /net/systems/jackett:/config
      - /net/systems/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  #plex:
  #  container_name: plex
  #  image: plexinc/pms-docker:public
  #  restart: unless-stopped
  #  environment:
  #    - TZ=America/Montreal
  #    - PLEX_CLAIM=claim-5oxrtYxamn3CqWfgzoNa
  #  network_mode: host
  #  volumes:
  #    - /net/data/systems/plex:/config
  #    - /net/data/systems/plex/temp:/transcode
  #    - /tmp:/tmp
  #    - /net/media/:/media
