# docker-compose file is managed by puppet
version: '3.5'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    volumes:
      - /net/data/systems/radarr:/config
      - /net/media/movies:/movies
      - /net/data/systems/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
    environment:
      - TZ=America/Montreal
      - PGID=1011
      - PUID=1011
    network_mode: host
    volumes:
      - /net/data/systems/transmission/config:/config
      - /net/data/systems/downloads:/downloads
      - /net/data/systems/downloads/watch:/watch
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    network_mode: host
    volumes:
      - /net/data/systems/sonarr:/config
      - /net/media/series:/series
      - /net/data/systems/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1011
      - PGID=1011
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /net/data/systems/jackett:/config
      - /net/data/systems/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.gameforce.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.gameforce.net'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '/net/data/systems/gitlab/config:/etc/gitlab'
      - '/net/data/systems/gitlab/logs:/var/log/gitlab'
      - '/net/data/systems/gitlab/data:/var/opt/gitlab'
  plex:
    container_name: plex
    image: plexinc/pms-docker:public
    restart: unless-stopped
    environment:
      - TZ=America/Montreal
      - PLEX_CLAIM=claim-5oxrtYxamn3CqWfgzoNa
    network_mode: host
    volumes:
      - /opt/plex:/config
      - /opt/plex/temp:/transcode
      - /tmp:/tmp
      - /net/media/:/medi