version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:public
    restart: unless-stopped
    environment:
      - TZ=America/Montreal
      - PLEX_CLAIM=claim-5oxrtYxamn3CqWfgzoNa
    network_mode: host
    volumes:
      - /net/data/systems/plex/database:/config
      - /net/data/systems/plex/temp:/transcode
      - /tmp:/tmp
      - /net/media/:/media
  sickchill:
    container_name: sickchill
    image: linuxserver/sickchill
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      - TZ=America/Montreal
      - PGID=1000
      - PUID=1000
    network_mode: host
    volumes:
      - /net/data/systems/sickchill/config:/config
      - /net/data/systems/downloads:/downloads
      - /net/media/series:/series
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
    environment:
      - TZ=America/Montreal
      - PGID=1000
      - PUID=1000
    network_mode: host
    volumes:
      - /net/data/systems/transmission/config:/config
      - /net/data/systems/downloads:/downloads
      - /net/data/systems/downloads/watch:/watch
