version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:public
    restart: unless-stopped
    environment:
      - TZ=America/Montreal
      - PLEX_CLAIM=claim-5oxrtYxamn3CqWfgzoNa
    network_mode: host
    volumes:
      - /net/data/systems/plex/database:/config
      - /net/data/systems/plex/temp:/transcode
      - /tmp:/tmp
      - /net/media/:/media
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    volumes:
      - /net/data/systems/radarr:/config
      - /net/media/movies:/movies
      - /net/data/systems/downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
    environment:
      - TZ=America/Montreal
      - PGID=1000
      - PUID=1000
    network_mode: host
    volumes:
      - /net/data/systems/transmission/config:/config
      - /net/data/systems/downloads:/downloads
      - /net/data/systems/downloads/watch:/watch
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    network_mode: host
    volumes:
      - /net/data/systems/sonarr:/config
      - /net/media/series:/series
      - /net/data/systems/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /net/data/systems/jackett:/config
      - /net/data/systems/downloads/complete:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - UMASK_SET=022 #optional
    volumes:
      - /net/data/systems/emby/:/config
      - /net/media/movies:/movies
      - /net/media/series:/series
      - /tmp:/transcode #optional
      #- /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    #devices:
      #- /dev/dri:/dev/dri #optional
      #- /dev/vchiq:/dev/vchiq #optional
      #- /dev/video10:/dev/video10 #optional
      #- /dev/video11:/dev/video11 #optional
      #- /dev/video12:/dev/video12 #optional
    restart: unless-stopped
  
