compose_sickrage:
version: '2'
services:
  sickrage:
    container_name: sickrage
    image: linuxserver/sickrage
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - TZ=America/Vancouver
      - PGID=1000
      - PUID=502
    network_mode: host
    volumes:
      - /net/systems/sickrage/config:/config
      - /net/systems/downloads:/downloads
      - /net/series:/series
