version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    mode: replicated
    environment:
      - TZ=America/Vancouver
      - PLEX_CLAIM=claim-5oxrtYxamn3CqWfgzoNa
    network_mode: host
    volumes:
      - /net/systems/plex/database:/config
      - /net/systems/plex/temp:/transcode
      - /net/:/data
