version: '2'
services:
  sickrage:
    container_name: sickrage
    image: linuxserver/sickrage
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - TZ=America/Vancouver
      - PGID=1001
      - PUID=100
    network_mode: host
    volumes:
      - /net/systems/sickrage/config:/config
      - /net/systems/downloads:/downloads
      - /net/series:/series
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        delay: 15s
        monitor: 15s
